FROM node:18-alpine AS build
RUN npm install -g pnpm
WORKDIR /app
COPY ["package.json", "pnpm-lock.yaml", "./"]
RUN pnpm install
COPY . .
RUN npm run build

FROM nginx:1.25.1-alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist/movies-db-ui .
ENTRYPOINT ["nginx", "-g", "daemon off;"]